openapi: 3.0.3
info:
  title: API Bibliothèque HEI
  description: Gestion de livres et des emprunts
  version: 1.0.0

servers:
  - url: https://api.hei.school/v1
  - url: https://staging.hei.school/v1
    description: Environnement de test

paths:
  /livres:
    get:
      summary: Lister les livres
      parameters:
        - in: query
          name: page
          description: Numéro de la page à récupérer
          schema:
            type: integer
            default: 1
        - in: query
          name: limit
          description: Nombres maximum de livres à retourner par page
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: Liste des livres trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Livre"
    post:
      summary: Créer un livre
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Livre"
      responses:
        "201":
          description: Livre créé
        "422":
          description: Données invalides

  /livres/{id}:
    get:
      summary: Récupérer un livre par son ID
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Livre trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Livre"
        "404":
          description: Livre introuvable

    put:
      summary: Remplacer un livre
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Livre"
      responses:
        "200":
          description: Livre mis à jour
        "404":
          description: Livre introuvable
        "422":
          description: Données invalides

    patch:
      summary: Modifier partiellement un livre
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Livre"
      responses:
        "200":
          description: Livre mis à jour partiellement
        "404":
          description: Livre introuvable
        "422":
          description: Données invalides

    delete:
      summary: Supprimer un livre
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Livre supprimé avec succès (sans corps de retour)
        "404":
          description: Livre introuvable

components:
  schemas:
    Livre:
      type: object
      required:
        - titre
      properties:
        id:
          type: integer
        titre:
          type: string
        auteur:
          type: string
